[package]
name = "aws-sig-auth"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "SigV4 signing middleware for the AWS SDK."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
sign-eventstream = ["aws-smithy-eventstream", "aws-sigv4/sign-eventstream"]

[dependencies]
aws-sigv4 = { path = "../aws-sigv4" }
aws-smithy-eventstream = { path = "../../../rust-runtime/aws-smithy-eventstream", optional = true }
aws-smithy-http = { path = "../../../rust-runtime/aws-smithy-http" }
aws-types = { path = "../aws-types" }
http = "0.2.2"
tracing = "0.1"

[dev-dependencies]
aws-endpoint = { path = "../aws-endpoint" }
tracing-test = "0.2.1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
