[package]
name = "aws-smithy-protocol-test"
version = "0.63.6"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "A collection of library functions to validate HTTP requests against Smithy protocol tests."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[dependencies]
# Not perfect for our needs, but good for now
assert-json-diff = "2"
base64-simd = "0.8"
cbor-diag = "0.1.12"
ciborium = "0.2"
http = "0.2.12"
pretty_assertions = "1.3"
regex-lite = "0.1.5"
roxmltree = "0.14.1"
serde_json = "1.0.128"
thiserror = "2"
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["client"] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
