# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "webassembly-wstd"
version = "0.1.0"
authors = [
    "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
    "Pat Hickey <pat@moreproductive.org>"
]
description = """
These tests ensure that things will fail (or not fail) as expected
when target is set to wasm32-wasip2 for all SDK and runtime crates.
"""
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"
publish = false

[target.'cfg(all(target_family = "wasm", target_env = "p2"))'.dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config", default-features = false, features = [
    "behavior-version-latest"
] }
aws-credential-types = { path = "../../build/aws-sdk/sdk/aws-credential-types", features = ["hardcoded-credentials"] }
aws-sdk-s3 = { path = "../../build/aws-sdk/sdk/s3", default-features = false }
aws-smithy-async = { path = "../../build/aws-sdk/sdk/aws-smithy-async", default-features = false }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http", default-features = false }
aws-smithy-http-client = { path = "../../build/aws-sdk/sdk/aws-smithy-http-client", default-features = false, features = ["test-util"] }
aws-smithy-runtime = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime", features = ["client"] }
aws-smithy-runtime-api = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime-api", features = ["client"] }
aws-smithy-types = { path = "../../build/aws-sdk/sdk/aws-smithy-types" }
aws-smithy-wasm = { path = "../../build/aws-sdk/sdk/aws-smithy-wasm" }
http-1x = { package = "http", version = "1" }
wstd = "0.6.5"
