# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "iam-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
aws-endpoint = { path = "../../build/aws-sdk/sdk/aws-endpoint" }
aws-http = { path = "../../build/aws-sdk/sdk/aws-http"}
aws-hyper = { path = "../../build/aws-sdk/sdk/aws-hyper", features = ["rustls"]}
aws-sdk-iam = { path = "../../build/aws-sdk/sdk/iam" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util", "rustls"] }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http", features = ["bytestream-util"] }
bytes = "1"
http = "0.2.3"
tokio = { version = "1", features = ["full", "test-util"]}
tracing-subscriber = "0.2.18"
