[package]
name = "smithy-xml"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

[dependencies]
xmlparser = "0.13.3"
thiserror = "1"
