repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: ^aws/rust-runtime/aws-sigv4/aws-sig-v4-test-suite/
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: kotlin-block-quotes
    name: Kotlin Block Quotes
    entry: ./.pre-commit-hooks/kotlin-block-quotes.py
    language: python
    files: ^.*\.kt$
  - id: license-header-check
    name: License Header Check
    entry: ./.pre-commit-hooks/license-header.sh
    language: system
    files: ^.*$
    pass_filenames: false
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-kotlin
    args: [--autofix, --ktlint-version, 0.48.2]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-rust
    entry: rustfmt --edition 2021
    files: ^.*\.rs$
