[workspace]
members = [
    "secretsmanager","kms","kinesis","dynamodb","smithy-types","smithy-http","smithy-http-tower","aws-auth","aws-endpoint","aws-types","aws-hyper","aws-sig-auth","examples/kms-helloworld","examples/dynamo-helloworld"
]
