[package]
name = "aws-smithy-wasm"
version = "0.0.0-smithy-rs-head"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
description = "Smithy WebAssembly configuration for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[target.'cfg(all(target_family = "wasm", target_os = "wasi"))'.dependencies]
aws-smithy-http = { path = "../aws-smithy-http" }
bytes = "1"
http = "0.2.4"
tower = { version = "0.4.8" }
wasi-preview2-prototype = { version = "0.0.2", features = ["http-client"] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
