[package]
name = "aws-smithy-wasm"
version = "0.1.7"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
  "Pat Hickey <pat@moreproductive.org>"
]
description = "Smithy WebAssembly wasip2 configuration for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
rust-version = "1.88"

[dependencies]
aws-smithy-async = { path = "../aws-smithy-async" }
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["http-1x"]}
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-types = { path = "../aws-smithy-types", features = ["http-body-1-x"] }
http-body-util = "0.1.2"
sync_wrapper = { version = "1", features = ["futures"] }
# Note the wstd crate will only build for target wasm32-wasip2, but having a target
# statement here breaks some of the CI tests, so we leave it with the rest of the deps
wstd = "0.6.5"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
