[package]
name = "aws-smithy-http"
version = "0.70.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Russell Cohen <rcoh@amazon.com>",
]
description = "Smithy HTTP logic for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[features]
event-stream = ["aws-smithy-eventstream"]
rt-tokio = ["aws-smithy-types/rt-tokio"]
compat = ["dep:http-02x"]

[dependencies]
aws-smithy-eventstream = { path = "../aws-smithy-eventstream", optional = true }
# FIXME(hyper1) - _somewhere_ in codegen relies on http-02x feature enabled via this crate, find and fix
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["client", "http-1x", "http-02x"] }
aws-smithy-types = { path = "../aws-smithy-types", features = ["byte-stream-poll-next", "http-body-0-4-x"] }
bytes = "1"
bytes-utils = "0.1"
http-1x = { package = "http", version = "1" }
http-02x = { package = "http", version = "0.2.9", optional = true }
# TODO(hyper1) - remove in favor of http-body-1x with breaking 0.70 change
http-body-04x = { package = "http-body", version = "0.4.4" }
http-body-1x = { package = "http-body", version = "1" }
once_cell = "1.10"
percent-encoding = "2.1.0"
pin-project-lite = "0.2.9"
pin-utils = "0.1.0"
tracing = "0.1"

# For an adapter to enable the `Stream` trait for `aws_smithy_types::byte_stream::ByteStream`
futures-core = "0.3.29"

[dev-dependencies]
async-stream = "0.3"
futures-util = { version = "0.3.29", default-features = false }
hyper = { version = "0.14.26", features = ["stream"] }
proptest = "1"
tokio = { version = "1.23.1", features = [
  "macros",
  "rt",
  "rt-multi-thread",
] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
