[package]
name = "dynamo-helloworld"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamodb = { version = "0.0.1", path = "../../build/aws-sdk/dynamodb" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
operation = { path = "../../build/aws-sdk/operation" }
auth = { path = "../../build/aws-sdk/auth" }
tokio = { version = "1", features = ["full"] }
http = "0.2.3"
env_logger = "0.8.2"
