[package]
name = "aws-sdk-dynamodb-mapper-core"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Core traits and types for the AWS SDK DynamoDB Mapper."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[dependencies]
aws-sdk-dynamodb = "1"
aws-smithy-types = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
