[package]
name = "sdk-perf"
version = "0.1.0"
edition = "2021"

[lib]
name = "sdk_perf"
path = "src/lib.rs"

[dependencies]
# SDK deps
# Note if you need more than dynamodb you will need to add the new services to the
# assemble command in the tools/ci-scripts/generate-sdk-perf-bin script
aws-config = {path = "../../build/aws-sdk/sdk/aws-config"}
aws-sdk-dynamodb = {path = "../../build/aws-sdk/sdk/dynamodb"}
aws-sdk-lambda = {path = "../../build/aws-sdk/sdk/lambda"}
aws-sdk-s3 = {path = "../../build/aws-sdk/sdk/s3"}
aws-smithy-runtime-api = {path = "../../build/aws-sdk/sdk/aws-smithy-runtime-api", features = ["http-1x"]}
aws-smithy-types = {path = "../../build/aws-sdk/sdk/aws-smithy-types"}
# External deps
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
http = "1.2.0"
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.133"
sysinfo = "0.30"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "s3_endpoint"
harness = false

[[bench]]
name = "lambda_endpoint"
harness = false
