[package]
name = "aws-smithy-observability-otel"
version = "0.1.3"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
]
description = "Smithy OpenTelemetry observability implementation."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-observability = { path = "../aws-smithy-observability" }
opentelemetry = {version = "0.27.0", features = ["metrics"]}
# The following dependencies are transitive and pinned for build
# compatability purposes
value-bag = "1.10.0"
async-global-executor = "2.4.1"
async-task = "=4.7.1"

# This crate cannot be used on powerpc or WASM (opentelemetry_sdk depends on async-std which doesn't support WASM)
[target.'cfg(all(not(target_arch = "powerpc"), not(target_family = "wasm")))'.dependencies]
opentelemetry_sdk = {version = "0.27.0", features = ["metrics", "testing"]}

[dev-dependencies]
tokio = { version = "1.23.1" }
criterion = {version = "0.5.1", features = ["async_tokio"]}
stats_alloc = "0.1.10"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata

[[bench]]
name = "sync_instruments"
harness = false

[[bench]]
name = "async_instruments"
harness = false
