[package]
name = "operationwip"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth = { path = "../auth" }
aws-sig-auth = { path = "../aws-sig-auth" }
http = "0.2.3"
bytes = "1"
tower = { version = "0.4.2", features = ["util"] }
http-body = "0.4.0"
pin-project = "1.0.4"
smithy-http = { path = "../../../rust-runtime/smithy-http"}

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
