[book]
title = "Smithy Rust"
authors = ["Russell Cohen", "aws-sdk-rust@amazon.com"]
language = "en"
src = "src"

[rust]
edition = "2021"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["static/mermaid.min.js", "static/mermaid-init.js"]
