[package]
name = "aws-smithy-runtime-api"
version = "1.10.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
description = "Smithy runtime types."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
client = []
http-auth = ["dep:zeroize"]
test-util = ["aws-smithy-types/test-util", "http-1x"]
http-02x = []
http-1x = []

[dependencies]
aws-smithy-async = { path = "../aws-smithy-async" }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1.10.0"
http-02x = { package = "http", version = "0.2.9" }
http-1x = { package = "http", version = "1" }
pin-project-lite = "0.2.14"
tokio = { version = "1.40.0", features = ["sync"] }
tracing = "0.1.40"
zeroize = { version = "1.7.0", optional = true }

[dev-dependencies]
proptest = "1"
tokio = { version = "1.25", features = ["macros", "rt", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata

# make sure to keep crate stability in sync with the second element of the following tuple in
# buildSrc/src/main/kotlin/CrateSet.kt:
#  Crate("aws-smithy-runtime-api", STABLE_VERSION_PROP_NAME),
[package.metadata.smithy-rs-release-tooling]
stable = true
