[package]
name = "sdk-sync"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "A CLI tool to replay commits from smithy-rs, generate code, and commit that code to aws-rust-sdk"
edition = "2021"
license = "Apache-2.0"
publish = false

# Having this here prevents this tool from being included in a higher-level workspace
[workspace]

[profile.release]
# prefer fast compile time over runtime performance
opt-level = 0

[dependencies]
anyhow = "1.0.56"
clap = { version = "~3.1.18", features = ["derive"] }
gitignore = "1.0.7"
num_cpus = "1.13.1"
rayon = "1.5.2"
serde = { version = "1.0.136", features = ["derive"] }
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }
systemstat = "0.1.11"
tempfile = "3.3.0"
toml = "0.5.9"
tracing = "0.1.34"
tracing-attributes = "0.1.20"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dev-dependencies]
mockall = "0.11.0"
once_cell = "1.10.0"
pretty_assertions = "1.2.1"
regex = "1.5.5"
tempfile = "3.3.0"
