[package]
name = "aws-smithy-legacy-http"
version = "0.62.9"
authors = [
    "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
    "Russell Cohen <rcoh@amazon.com>",
]
description = "Smithy HTTP-0x logic for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"
rust-version = "1.91"

[features]
event-stream = ["aws-smithy-eventstream"]
rt-tokio = ["aws-smithy-types/rt-tokio"]

[dependencies]
aws-smithy-eventstream = { path = "../aws-smithy-eventstream", optional = true }
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["client", "http-02x"] }
aws-smithy-types = { path = "../aws-smithy-types", features = ["byte-stream-poll-next", "http-body-0-4-x"] }
bytes = "1.10.0"
bytes-utils = "0.1"
# TODO(hyper1) - Complete the breaking changes by updating to http 1.x ecosystem fully in this crate. Also remove hyper 0.14 from dev
http-02x = { package = "http", version = "0.2.12" }
http-1x = { package = "http", version = "1.3.1" }
http-body-04x = { package = "http-body", version = "0.4.6" }
percent-encoding = "2.3.1"
pin-project-lite = "0.2.14"
pin-utils = "0.1.0"
tracing = "0.1.40"

# For an adapter to enable the `Stream` trait for `aws_smithy_types::byte_stream::ByteStream`
futures-core = "0.3.31"
futures-util = { version = "0.3.29", default-features = false }

[dev-dependencies]
async-stream = "0.3"
futures-util = { version = "0.3.29", default-features = false }
hyper = { version = "0.14.26", features = ["stream"] }
proptest = "1"
tokio = { version = "1.23.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
