[package]
name = "aws-hyper"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.2", features = ["client", "http1", "http2"] }
tower = "0.4.2"
operation = { path = "../operation" }
middleware-tracing = { path = "../middleware-tracing" }
hyper-tls = "0.5.0"
auth  = { path = "../auth" }
http = "0.2.3"
bytes = "1"
http-body = "0.4.0"
pin-utils = "0.1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"]}
