[package]
name = "aws-hyper"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.2", features = ["client", "http1", "http2"] }
tower = { version = "0.4.2", features = ["retry", "buffer"] }
operationwip = { path = "../operationwip" }
middleware-tracing = { path = "../middleware-tracing" }
hyper-tls = "0.5.0"
auth  = { path = "../auth" }
aws-sig-auth = { path = "../aws-sig-auth" }
http = "0.2.3"
bytes = "1"
http-body = "0.4.0"
tokio = { version = "1", features = ["time"]}
smithy-http = { path = "../../../rust-runtime/smithy-http" }
pin-utils = "0.1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"]}
tower-test = "0.4.0"
