[package]
name = "aws-types"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Cross-service types for the AWS SDK."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
hardcoded-credentials = []

[dependencies]
aws-smithy-async = { path = "../../../rust-runtime/aws-smithy-async" }
aws-smithy-types = { path = "../../../rust-runtime/aws-smithy-types" }
aws-smithy-client = { path = "../../../rust-runtime/aws-smithy-client" }
tracing = "0.1"
zeroize = "1.4.1"

[dev-dependencies]
futures-util = "0.3.16"
tracing-test = "0.2.1"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
