[package]
name = "ses-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

[dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config" }
aws-sdk-sesv2 = { path = "../../build/aws-sdk/sdk/sesv2" }
aws-types = { path = "../../build/aws-sdk/sdk/aws-types" }

tokio = { version = "1", features = ["full"] }

structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
