[package]
name = "publisher"
version = "0.4.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Tool used to publish the AWS SDK to crates.io"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[profile.release]
# prefer fast compile time over runtime performance
opt-level = 0

[dependencies]
anyhow = "1.0"
async-recursion = "0.3.2"
async-trait = "0.1.51"
cargo_toml = "0.10.1"
clap = { version = "~3.1.18", features = ["derive"] }
crates_io_api = "0.7.3"
dialoguer = "0.8"
handlebars = "4.2"
lazy_static = "1"
num_cpus = "1.13"
regex = "1.5.4"
reqwest = "0.11.10"
semver = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha256 = "1"
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common", features = ["async-shell"] }
thiserror = "1.0"
tokio = { version = "1.12", features = ["full"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
