[package]
name = "pokemon-service-common"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "A smithy Rust service to retrieve information about Pok√©mon."

[dependencies]
async-stream = "0.3"
http = "0.2.9"
rand = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
tokio = { version = "1", default-features = false, features = ["time"] }
tower = "0.4"

# Local paths
aws-smithy-runtime = { path = "../../../rust-runtime/aws-smithy-runtime", features = ["client", "connector-hyper-0-14-x", "tls-rustls"] }
aws-smithy-runtime-api = { path = "../../../rust-runtime/aws-smithy-runtime-api", features = ["client"] }
pokemon-service-client = { path = "../pokemon-service-client/", package = "pokemon-service-client", features = [
    "behavior-version-latest",
] }
pokemon-service-server-sdk = { path = "../pokemon-service-server-sdk", package = "pokemon-service-server-sdk-http0x" }

[dev-dependencies]
aws-smithy-runtime = { path = "../../../rust-runtime/aws-smithy-runtime", features = ["test-util"] }
