[package]
name = "changelogger"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "A CLI tool render and update changelogs from TOML changelog files"
edition = "2021"
license = "Apache-2.0"
publish = false

# Having this here prevents this tool from being included in a higher-level workspace
[workspace]

[profile.release]
# prefer fast compile time over runtime performance
opt-level = 0

[dependencies]
anyhow = "1.0.57"
clap = { version = "~3.2.1", features = ["derive"] }
once_cell = "1.15.0"
ordinal = "0.3.2"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
smithy-rs-tool-common = { path = "../smithy-rs-tool-common" }
time = { version = "0.3.9", features = ["local-offset"]}
toml = "0.5.8"

[dev-dependencies]
pretty_assertions = "1.3"
tempfile = "3.3.0"
