# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "webassembly"
version = "0.1.0"
authors = [
    "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
description = """
These tests ensure that things will fail (or not fail) as expected
when target is set to wasm32-wasip1 for all SDK and runtime crates.
"""
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"
publish = false


[features]
default = ["test-util"]
test-util = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_family = "wasm")'.dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config", default-features = false, features = [
    "rt-tokio",
    "behavior-version-latest"
] }
aws-credential-types = { path = "../../build/aws-sdk/sdk/aws-credential-types", features = ["hardcoded-credentials"] }
aws-sdk-s3 = { path = "../../build/aws-sdk/sdk/s3", default-features = false }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
aws-smithy-runtime = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime", features = ["client"] }
aws-smithy-runtime-api = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime-api", features = ["client"] }
aws-smithy-types = { path = "../../build/aws-sdk/sdk/aws-smithy-types" }
aws-smithy-wasm = { path = "../../build/aws-sdk/sdk/aws-smithy-wasm" }
http = "0.2.9"
tokio = { version = "1.32.0", features = ["macros", "rt"] }

[target.'cfg(all(target_family = "wasm", target_env = "p1"))'.dependencies]
wit-bindgen = { version = "0.16.0", features = ["macros", "realloc"] }

[lib]
crate-type = ["cdylib"]

# metadata used by cargo-component to identify which wit world to embed in the binary
[package.metadata.component]
package = "aws:component"
