[package]
name = "aws-sigv4"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "David Barsky <me@davidbarsky.com>"]
description = "SigV4 signer for HTTP requests and Event Stream messages."
edition = "2021"
exclude = ["aws-sig-v4-test-suite/*"]
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
sign-http = ["http", "percent-encoding", "form_urlencoded"]
sign-eventstream = ["aws-smithy-eventstream", "bytes"]
default = ["sign-http"]

[dependencies]
aws-smithy-eventstream = { path = "../../../rust-runtime/aws-smithy-eventstream", optional = true }
aws-smithy-http = { path = "../../../rust-runtime/aws-smithy-http" }
bytes = { version = "1", optional = true }
form_urlencoded = { version = "1.0", optional = true }
hex = "0.4"
http = { version = "0.2", optional = true }
once_cell = "1.8"
percent-encoding = { version = "2.1", optional = true }
regex = "1.5"
time = "0.3.5"
tracing = "0.1"
hmac = "0.12"
sha2 = "0.10"

[dev-dependencies]
criterion = "0.4"
bytes = "1"
httparse = "1.5"
pretty_assertions = "1.3"
proptest = "1.2"
time = { version = "0.3.4", features = ["parsing"] }

[target.'cfg(not(any(target_arch = "powerpc", target_arch = "powerpc64")))'.dev-dependencies]
ring = "0.16"

[[bench]]
name = "hmac"
harness = false

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
