[package]
name = "compiletime-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/aws-config" }
aws-sdk-batch = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/batch" }
aws-sdk-cloudcontrol = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/cloudcontrol" }
aws-sdk-ec2 = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/ec2" }
aws-sdk-iam = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/iam" }
aws-sdk-resourceexplorer2 = { features = ["serde-serialize", "serde-deserialize"], path ="./serde-aws-sdk/sdk/resourceexplorer2" }
env_logger = "0.10.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["tokio-macros", "macros", "rt-multi-thread"] }
toml = "0.7.1"

[build]
rustflags = ["--cfg", "aws-sdk-unstable"]