[package]
name = "pokemon_service"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "A smithy Rust service to retrieve information about Pok√©mon."

[dependencies]
clap = { version = "~3.2.1", features = ["derive"] }
hyper = {version = "0.14", features = ["server"] }
tokio = "1"
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Local paths
aws-smithy-http-server = { path = "../../" }
pokemon_service_sdk = { path = "../pokemon_service_sdk/" }

[dev-dependencies]
assert_cmd = "2.0"
home = "0.5"
wrk-api-bench = "0.0.7"

# Local paths
aws-smithy-client  = { path = "../../../aws-smithy-client/", features = ["rustls"] }
pokemon_service_client = { path = "../pokemon_service_client/" }
