allowed_external_types = [
    "aws_types::*",
    "aws_credential_types::*",
    "aws_smithy_http::*",
    "aws_smithy_runtime_api::*",

    "http::error::Error",
    "http::header::map::HeaderMap",
    "http::header::value::HeaderValue",
    "http::method::Method",
    "http::request::Request",
    "http::uri::Uri",
]
